fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -90,8 +90,18 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: 6942ba1f6b715cd46e99b6254e76ca324a48f7f8
-        with:
-          fail-fast: true
+      - name: SonarCloud Quality Gate Check
+        env:
+          SONAR_TOKEN: 6942ba1f6b715cd46e99b6254e76ca324a48f7f8
+        run: |
+          quality_gate=$(curl -s -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Sotatek-HungPham3_qlks_fe&branch=<master&sonarVersion=8.0" \
+              -H "accept: application/json" \
+              -H "Authorization: Basic 6942ba1f6b715cd46e99b6254e76ca324a48f7f8")
+          status=$(echo "$quality_gate" | jq -r '.projectStatus.status')
+          if [ "$status" != "OK" ]; then
+              echo "Quality Gate status is $status, failing build..."
+              exit 1
+          fi
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
